/** Portfolio grid column metadata (labels, tooltips, formulas, column groups). */

export const PORTFOLIO_COLUMN_GROUPS = [
  { id: 'quote', label: 'Quote' },
  { id: 'returns', label: 'Returns' },
  { id: 'range52w', label: '52-Week' },
  { id: 'valuation', label: 'Valuation' },
  { id: 'ratios', label: 'Ratios' },
  { id: 'cashflow', label: 'Cash Flow' },
  { id: 'insider', label: 'Insider' },
  { id: 'links', label: 'Links' },
];

/** Default visible columns — extended metrics hidden until user enables them. */
export const PORTFOLIO_DEFAULT_VISIBLE_COLUMNS = [
  'select',
  'ticker',
  'price',
  'change',
  'marketCap',
  'sector',
  'tags',
  'change1w',
  'change6m',
  'pctTo52wHi',
  'sp',
  'ep',
  'ebitdaEv',
  'sfcfp',
  'insiderBuy6m',
  'secLink',
  'chartLink',
];

export const PORTFOLIO_COLUMN_META = {
  ticker: {
    label: 'Ticker',
    shortLabel: 'Ticker',
    fullName: 'Ticker Symbol',
    group: 'quote',
    sticky: true,
  },
  price: {
    label: 'Price',
    shortLabel: 'Price',
    fullName: 'Latest Price',
    tooltip: 'Daily closing price used throughout the platform. Intraday movements are not reflected.',
    formula: 'Latest close from prices cache',
    source: 'Stooq / yfinance → SQLite prices',
    group: 'quote',
    sticky: true,
  },
  change: {
    label: 'Change',
    shortLabel: 'D% Ch',
    fullName: 'Daily Percent Change',
    tooltip: 'One-day price movement. Short-term volatility can be noisy; longer lookback periods often provide better trend context.',
    formula: '(todayClose - prevClose) / prevClose × 100',
    source: 'SQLite prices (daily change)',
    group: 'quote',
    heat: 'signed',
    heatScale: 5,
  },
  marketCap: {
    label: 'Market Cap',
    shortLabel: 'Mkt Cap',
    fullName: 'Market Capitalization',
    tooltip: 'Equity value based on shares outstanding and market price. Does not include debt; enterprise value provides a fuller measure of company value.',
    formula: 'shares outstanding × latest close',
    source: 'SEC shares + prices',
    group: 'quote',
  },
  sector: {
    label: 'Sector',
    shortLabel: 'Sector',
    fullName: 'Sector',
    tooltip: 'Derived from SEC SIC classifications and used for peer comparisons and percentile rankings throughout the platform.',
    source: 'SEC submissions',
    group: 'quote',
  },
  tags: {
    label: 'Tags',
    shortLabel: 'Tags',
    fullName: 'Portfolio Tags',
    tooltip: 'User-defined tags for filtering and themes',
    group: 'quote',
  },
  industry: {
    label: 'Industry',
    shortLabel: 'Sub-Ind',
    fullName: 'Industry / Sub-Industry',
    tooltip: 'More granular than sector and useful for identifying direct competitors. Classifications may lag corporate restructurings or spin-offs.',
    source: 'SEC submissions',
    group: 'quote',
  },
  change1w: {
    label: '1W %',
    shortLabel: 'W% Ch',
    fullName: '1-Week Percent Change',
    tooltip: 'Percent change vs ~5 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 8,
  },
  change4w: {
    label: '4W %',
    shortLabel: '4W% Ch',
    fullName: '4-Week Percent Change',
    tooltip: 'Percent change vs ~20 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 12,
  },
  change6m: {
    label: '6M %',
    shortLabel: '6M% Ch',
    fullName: '6-Month Percent Change',
    tooltip: 'Percent change vs ~126 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 20,
  },
  pctTo52wHi: {
    label: '% to 52W Hi',
    shortLabel: 'To 52H',
    fullName: 'Percent Distance to 52-Week High',
    tooltip: 'Distance from the trailing 52-week high. Values closer to zero indicate the stock is trading near its recent peak.',
    formula: '(price − 52w high) / 52w high × 100',
    group: 'range52w',
    heat: 'signed',
    heatScale: 15,
  },
  pctFrom52wLo: {
    label: '% from 52W Lo',
    shortLabel: 'Fr 52L',
    fullName: 'Percent Above 52-Week Low',
    tooltip: 'Measures how far the stock has recovered from its trailing 52-week low. Useful for evaluating recovery strength and trend persistence.',
    formula: '(price − 52w low) / 52w low × 100',
    group: 'range52w',
    heat: 'signed',
    heatScale: 30,
  },
  revenue: {
    label: 'Revenue',
    shortLabel: 'Rev TTM',
    fullName: 'Revenue (latest annual)',
    tooltip: 'Annual revenue from the latest reported fiscal year. May differ materially from trailing twelve-month performance.',
    source: 'SEC CompanyFacts',
    group: 'valuation',
  },
  sp: {
    label: 'SP',
    shortLabel: 'S/P',
    fullName: 'Sales per Share',
    tooltip: 'Revenue generated per share outstanding. Useful when comparing companies with different margin profiles or companies not yet consistently profitable.',
    formula: 'revenue / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ebitdaEv: {
    label: 'Eb/EV',
    shortLabel: 'Eb/EV',
    fullName: 'EBITDA / Enterprise Value',
    tooltip: 'EBITDA divided by enterprise value (inverse EV/EBITDA). Higher values generally indicate more operating earnings relative to enterprise value, though results can be distorted by cyclical peaks or negative EBITDA.',
    formula: 'ebitda / (marketCap + debt - cash)',
    source: 'SEC + prices (derived)',
    group: 'valuation',
    heat: 'column',
  },
  tbp: {
    label: 'TBP',
    shortLabel: 'TB/P',
    fullName: 'Tangible Book per Share',
    tooltip: 'Tangible book value per share. Excludes goodwill and most intangible assets, making it most useful for asset-heavy businesses.',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  bp: {
    label: 'BP',
    shortLabel: 'B/P',
    fullName: 'Book Value per Share',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ep: {
    label: 'EP',
    shortLabel: 'E/P',
    fullName: 'Earnings per Share',
    tooltip: 'Earnings per share from the latest filing. Best interpreted alongside historical trends rather than as a standalone value.',
    formula: 'EPS (diluted)',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  pe: {
    label: 'P/E',
    shortLabel: 'P/E',
    fullName: 'Price / Earnings',
    tooltip: 'Price relative to earnings per share. Lower values may indicate lower earnings valuation, but negative earnings make the ratio meaningless. Best interpreted alongside growth, profitability, and balance-sheet quality.',
    formula: 'price / EPS',
    source: 'SEC CompanyFacts + prices',
    group: 'valuation',
    heat: 'column',
    higherIsBetter: false,
  },
  revDebt: {
    label: 'Rev/Debt',
    shortLabel: 'Rev/Debt',
    fullName: 'Revenue / Total Debt',
    tooltip: 'Compares annual revenue to total debt. Useful as a rough leverage screen but should be evaluated alongside margins, cash flow, and interest coverage.',
    group: 'valuation',
    heat: 'column',
  },
  de: {
    label: 'D/E',
    shortLabel: 'D/E',
    fullName: 'Debt / Equity',
    tooltip: 'Debt-to-equity ratio. Higher values indicate greater financial leverage, though appropriate levels vary substantially by industry.',
    formula: 'debt / equity',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
    higherIsBetter: false,
  },
  mcEv: {
    label: 'MC/EV',
    shortLabel: 'MC/EV',
    fullName: 'Market Cap / Enterprise Value',
    tooltip: 'Measures the proportion of enterprise value represented by equity rather than debt. Lower values generally indicate heavier reliance on debt financing.',
    group: 'valuation',
    heat: 'column',
  },
  currentRatio: {
    label: 'Cur Ratio',
    shortLabel: 'Cur R',
    fullName: 'Current Ratio',
    tooltip: 'Current assets divided by current liabilities. Below 1.0 may indicate liquidity pressure, though interpretation depends on industry and working-capital structure.',
    formula: 'assetsCurrent / liabilitiesCurrent',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  grossMargin: {
    label: 'Gross Mgn',
    shortLabel: 'GM%',
    fullName: 'Gross Margin',
    tooltip: 'Gross profit ÷ revenue (latest annual SEC). Software 80%+ is normal; insurers/utilities may not map COGS cleanly in XBRL.',
    formula: 'grossProfit / revenue',
    source: 'SEC CompanyFacts — GrossProfit tag, or revenue − CostOfRevenue',
    group: 'valuation',
    heat: 'column',
  },
  netMargin: {
    label: 'Net Mgn',
    shortLabel: 'NM%',
    fullName: 'Net Margin',
    tooltip: 'Percentage of revenue retained as net income. Useful for tracking profitability trends over time.',
    formula: 'netIncome / revenue',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  roe: {
    label: 'ROE',
    shortLabel: 'ROE',
    fullName: 'Return on Equity',
    tooltip: 'Measures profit generated per dollar of shareholder equity. High values may result from operational efficiency, leverage, or share repurchases.',
    formula: 'netIncome / equity',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  roa: {
    label: 'ROA',
    shortLabel: 'ROA',
    fullName: 'Return on Assets',
    tooltip: 'Measures profit generated per dollar of assets. Useful for comparing operational efficiency across companies with different capital structures.',
    formula: 'netIncome / assets',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  divYield: {
    label: 'Div Yield',
    shortLabel: 'Div%',
    fullName: 'Dividend Yield',
    tooltip: 'Annual dividend yield based on current share price. High yields may reflect either shareholder returns or concerns about payout sustainability.',
    formula: 'abs(ncfdiv) / shares / price',
    source: 'SEC CompanyFacts + prices',
    group: 'valuation',
    heat: 'column',
  },
  operatingMargin: {
    label: 'Op Mgn',
    shortLabel: 'Op%',
    fullName: 'Operating Margin',
    tooltip: 'Operating income as % of revenue. Compression may signal competitive pressure or operating deleverage.',
    formula: 'operating income / revenue',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
  },
  fcfMargin: {
    label: 'FCF Mgn',
    shortLabel: 'FCF%',
    fullName: 'FCF Margin',
    tooltip: 'Free cash flow as % of revenue. Higher values indicate stronger cash conversion and reinvestment flexibility.',
    formula: 'free cash flow / revenue',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
  },
  quickRatio: {
    label: 'Quick R',
    shortLabel: 'Quick',
    fullName: 'Quick Ratio',
    tooltip: 'Liquid assets (excluding inventory) vs current liabilities. Below 1.0 may indicate near-term liquidity stress depending on industry.',
    formula: '(current assets − inventory) / current liabilities',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
  },
  interestCoverage: {
    label: 'Int Cov',
    shortLabel: 'IntCov',
    fullName: 'Interest Coverage',
    tooltip: 'EBIT relative to interest expense. Low coverage limits debt capacity and raises default sensitivity.',
    formula: 'EBIT / interest expense',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
  },
  roic: {
    label: 'ROIC',
    shortLabel: 'ROIC',
    fullName: 'Return on Invested Capital',
    tooltip: 'NOPAT on invested capital (debt + equity − cash). Sustained high ROIC often signals durable competitive advantage.',
    formula: 'NOPAT / (debt + equity − cash)',
    source: 'SEC CompanyFacts (derived)',
    group: 'ratios',
    heat: 'column',
  },
  evEbitda: {
    label: 'EV/EBITDA',
    shortLabel: 'EV/Eb',
    fullName: 'EV / EBITDA',
    tooltip: 'Enterprise value relative to EBITDA. Lower multiples often indicate cheaper operating earnings; cyclical swings can distort.',
    formula: '(marketCap + debt − cash) / EBITDA',
    source: 'SEC CompanyFacts + prices (derived)',
    group: 'ratios',
    heat: 'column',
    higherIsBetter: false,
  },
  fcfYield: {
    label: 'FCF Yield',
    shortLabel: 'FCF Yld',
    fullName: 'FCF Yield',
    tooltip: 'Free cash flow relative to enterprise value. Higher yields suggest stronger cash return on the capital base.',
    formula: 'free cash flow / enterprise value',
    source: 'SEC CompanyFacts + prices (derived)',
    group: 'ratios',
    heat: 'column',
  },
  netDebt: {
    label: 'Net Debt',
    shortLabel: 'Net D',
    fullName: 'Net Debt',
    tooltip: 'Total debt minus cash. Positive net debt means the firm owes more than it holds in cash.',
    formula: 'total debt − cash & equivalents',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
    higherIsBetter: false,
  },
  earningsYield: {
    label: 'E/P',
    shortLabel: 'E/P',
    fullName: 'Earnings Yield',
    tooltip: 'Inverse of P/E — earnings power relative to price. Higher yields may indicate value.',
    formula: 'EPS / price',
    source: 'SEC CompanyFacts + prices',
    group: 'ratios',
    heat: 'column',
  },
  assetTurnover: {
    label: 'Asset Turn',
    shortLabel: 'AT',
    fullName: 'Asset Turnover',
    tooltip: 'Revenue per dollar of assets. Higher turnover reflects asset efficiency.',
    formula: 'revenue / total assets',
    source: 'SEC CompanyFacts',
    group: 'ratios',
    heat: 'column',
  },
  cfop: {
    label: 'CFOP',
    shortLabel: 'CFO/P',
    fullName: 'Cash Flow from Operations per Share',
    tooltip: 'Operating cash flow per share. Often viewed alongside earnings to evaluate cash-generation quality.',
    formula: 'operating cash flow / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'cashflow',
    heat: 'column',
  },
  sfcfp: {
    label: 'SFCFP',
    shortLabel: 'SFCF/P',
    fullName: 'Free Cash Flow per Share',
    tooltip: 'Free cash flow per share after capital expenditures. Useful for evaluating a company\'s ability to fund growth, debt reduction, or shareholder returns.',
    formula: '(operating cash flow - capex) / shares outstanding',
    source: 'SEC CompanyFacts (derived)',
    group: 'cashflow',
    heat: 'column',
  },
  ncfp: {
    label: 'NCFP',
    shortLabel: 'NCF/P',
    fullName: 'Net Cash Flow per Share',
    tooltip: 'Net cash flow per share including operating, investing, and financing activities. Useful for identifying major financing or restructuring activity.',
    group: 'cashflow',
    heat: 'column',
  },
  cashp: {
    label: 'Cash/P',
    shortLabel: 'Cash/P',
    fullName: 'Cash per Share',
    tooltip: 'Cash and equivalents per share. Compare against debt levels to evaluate net cash or net debt positioning.',
    group: 'cashflow',
    heat: 'column',
  },
  assetp: {
    label: 'Asset/P',
    shortLabel: 'Asset/P',
    fullName: 'Assets per Share',
    tooltip: 'Assets per share. Most useful for asset-heavy businesses such as banks, insurers, REITs, and industrial firms.',
    group: 'cashflow',
    heat: 'column',
  },
  divergenceSignal: {
    label: 'Divergence',
    shortLabel: 'Div',
    fullName: 'Narrative Divergence Signal',
    tooltip: 'Fundamental vs sentiment divergence classification',
    source: 'Narrative intelligence snapshots',
    group: 'insider',
  },
  divergenceScore: {
    label: 'Div Score',
    shortLabel: 'Div#',
    fullName: 'Narrative Divergence Score',
    tooltip: 'Measures disagreement between fundamentals and market narrative. Higher values suggest business performance and investor sentiment are moving in different directions.',
    source: 'Narrative intelligence snapshots',
    group: 'insider',
    heat: 'column',
  },
  insiderBuy6m: {
    label: 'Insider Buy 6M',
    shortLabel: '6M IB',
    fullName: 'Insider Buying (6 months)',
    tooltip: 'Net open-market insider purchases over the past 6 months. Includes Form 4 purchase transactions above platform thresholds and excludes compensation-related grants.',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy3m: {
    label: 'Insider Buy 3M',
    shortLabel: '3M IB',
    fullName: 'Insider Buying (3 months)',
    tooltip: 'Net open-market insider purchases over the past 3 months. Includes Form 4 purchase transactions above platform thresholds and excludes compensation-related grants.',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy1m: {
    label: 'Insider Buy 1M',
    shortLabel: '1M IB',
    fullName: 'Insider Buying (1 month)',
    tooltip: 'Net open-market insider purchases over the past month. Includes Form 4 purchase transactions above platform thresholds and excludes compensation-related grants.',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  secLink: { label: 'SEC', shortLabel: 'SEC', group: 'links' },
  wwLink: { label: 'Inst', shortLabel: 'Inst', group: 'links' },
  saLink: { label: 'Analysis', shortLabel: 'Anlys', group: 'links' },
  newsLink: { label: 'News', shortLabel: 'News', group: 'links' },
  chartLink: { label: 'Chart', shortLabel: 'Chart', group: 'links' },
  openInsiderLink: { label: 'Insiders', shortLabel: 'Ins', group: 'links' },
};
