/** Portfolio grid column metadata (labels, tooltips, formulas, column groups). */

export const PORTFOLIO_COLUMN_GROUPS = [
  { id: 'quote', label: 'Quote' },
  { id: 'returns', label: 'Returns' },
  { id: 'range52w', label: '52-Week' },
  { id: 'valuation', label: 'Valuation' },
  { id: 'cashflow', label: 'Cash Flow' },
  { id: 'insider', label: 'Insider' },
  { id: 'links', label: 'Links' },
];

/** Default visible columns — extended metrics hidden until user enables them. */
export const PORTFOLIO_DEFAULT_VISIBLE_COLUMNS = [
  'select',
  'ticker',
  'price',
  'change',
  'marketCap',
  'sector',
  'change1w',
  'change6m',
  'pctTo52wHi',
  'sp',
  'ep',
  'ebitdaEv',
  'sfcfp',
  'insiderBuy6m',
  'secLink',
  'chartLink',
];

export const PORTFOLIO_COLUMN_META = {
  ticker: {
    label: 'Ticker',
    shortLabel: 'Ticker',
    fullName: 'Ticker Symbol',
    tooltip: 'Stock ticker symbol',
    group: 'quote',
    sticky: true,
  },
  price: {
    label: 'Price',
    shortLabel: 'Price',
    fullName: 'Latest Price',
    tooltip: 'Latest closing price (USD)',
    formula: 'Latest close from prices cache',
    source: 'Stooq / yfinance → SQLite prices',
    group: 'quote',
    sticky: true,
  },
  change: {
    label: 'Change',
    shortLabel: 'D% Ch',
    fullName: 'Daily Percent Change',
    tooltip: 'Percent change from previous close',
    formula: '(todayClose - prevClose) / prevClose × 100',
    source: 'SQLite prices (daily change)',
    group: 'quote',
    heat: 'signed',
    heatScale: 5,
  },
  marketCap: {
    label: 'Market Cap',
    shortLabel: 'Mkt Cap',
    fullName: 'Market Capitalization',
    tooltip: 'Market capitalization (USD)',
    formula: 'shares outstanding × latest close',
    source: 'SEC shares + prices',
    group: 'quote',
  },
  sector: {
    label: 'Sector',
    shortLabel: 'Sector',
    fullName: 'Sector',
    tooltip: 'Coarse sector from SEC SIC code',
    source: 'SEC submissions',
    group: 'quote',
  },
  industry: {
    label: 'Industry',
    shortLabel: 'Sub-Ind',
    fullName: 'Industry / Sub-Industry',
    tooltip: 'SEC SIC industry description',
    source: 'SEC submissions',
    group: 'quote',
  },
  change1w: {
    label: '1W %',
    shortLabel: 'W% Ch',
    fullName: '1-Week Percent Change',
    tooltip: 'Percent change vs ~5 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 8,
  },
  change4w: {
    label: '4W %',
    shortLabel: '4W% Ch',
    fullName: '4-Week Percent Change',
    tooltip: 'Percent change vs ~20 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 12,
  },
  change6m: {
    label: '6M %',
    shortLabel: '6M% Ch',
    fullName: '6-Month Percent Change',
    tooltip: 'Percent change vs ~126 trading days ago',
    group: 'returns',
    heat: 'signed',
    heatScale: 20,
  },
  pctTo52wHi: {
    label: '% to 52W Hi',
    shortLabel: 'To 52H',
    fullName: 'Percent Distance to 52-Week High',
    tooltip: '(price - 52w high) / 52w high × 100',
    group: 'range52w',
    heat: 'signed',
    heatScale: 15,
  },
  pctFrom52wLo: {
    label: '% from 52W Lo',
    shortLabel: 'Fr 52L',
    fullName: 'Percent Above 52-Week Low',
    tooltip: '(price - 52w low) / 52w low × 100',
    group: 'range52w',
    heat: 'signed',
    heatScale: 30,
  },
  revenue: {
    label: 'Revenue',
    shortLabel: 'Rev TTM',
    fullName: 'Revenue (latest annual)',
    tooltip: 'Latest annual revenue from SEC filings',
    source: 'SEC CompanyFacts',
    group: 'valuation',
  },
  sp: {
    label: 'SP',
    shortLabel: 'S/P',
    fullName: 'Sales per Share',
    tooltip: 'Revenue per share',
    formula: 'revenue / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ebitdaEv: {
    label: 'Eb/EV',
    shortLabel: 'Eb/EV',
    fullName: 'EBITDA / Enterprise Value',
    tooltip: 'EBITDA divided by enterprise value',
    formula: 'ebitda / (marketCap + debt - cash)',
    source: 'SEC + prices (derived)',
    group: 'valuation',
    heat: 'column',
  },
  tbp: {
    label: 'TBP',
    shortLabel: 'TB/P',
    fullName: 'Tangible Book per Share',
    tooltip: 'Book value per share (tangible proxy)',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  bp: {
    label: 'BP',
    shortLabel: 'B/P',
    fullName: 'Book Value per Share',
    tooltip: 'Book value per share',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ep: {
    label: 'EP',
    shortLabel: 'E/P',
    fullName: 'Earnings per Share',
    tooltip: 'Diluted EPS from latest annual filing',
    formula: 'EPS (diluted)',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  pe: {
    label: 'P/E',
    shortLabel: 'P/E',
    fullName: 'Price / Earnings',
    tooltip: 'Price divided by diluted EPS',
    formula: 'price / EPS',
    source: 'SEC CompanyFacts + prices',
    group: 'valuation',
    heat: 'column',
  },
  revDebt: {
    label: 'Rev/Debt',
    shortLabel: 'Rev/Debt',
    fullName: 'Revenue / Total Debt',
    tooltip: 'Latest revenue divided by total debt',
    group: 'valuation',
    heat: 'column',
  },
  de: {
    label: 'D/E',
    shortLabel: 'D/E',
    fullName: 'Debt / Equity',
    tooltip: 'Total debt divided by shareholders equity',
    formula: 'debt / equity',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  mcEv: {
    label: 'MC/EV',
    shortLabel: 'MC/EV',
    fullName: 'Market Cap / Enterprise Value',
    tooltip: 'Equity weight in capital structure proxy',
    group: 'valuation',
    heat: 'column',
  },
  currentRatio: {
    label: 'Cur Ratio',
    shortLabel: 'Cur R',
    fullName: 'Current Ratio',
    tooltip: 'Current assets / current liabilities',
    formula: 'assetsCurrent / liabilitiesCurrent',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  grossMargin: {
    label: 'Gross Mgn',
    shortLabel: 'GM%',
    fullName: 'Gross Margin',
    tooltip: 'Gross profit / revenue',
    formula: 'grossProfit / revenue',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  netMargin: {
    label: 'Net Mgn',
    shortLabel: 'NM%',
    fullName: 'Net Margin',
    tooltip: 'Net income / revenue',
    formula: 'netIncome / revenue',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  roe: {
    label: 'ROE',
    shortLabel: 'ROE',
    fullName: 'Return on Equity',
    tooltip: 'Net income / shareholders equity',
    formula: 'netIncome / equity',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  roa: {
    label: 'ROA',
    shortLabel: 'ROA',
    fullName: 'Return on Assets',
    tooltip: 'Net income / total assets',
    formula: 'netIncome / assets',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  divYield: {
    label: 'Div Yield',
    shortLabel: 'Div%',
    fullName: 'Dividend Yield',
    tooltip: 'Dividends per share / price',
    formula: 'abs(ncfdiv) / shares / price',
    source: 'SEC CompanyFacts + prices',
    group: 'valuation',
    heat: 'column',
  },
  cfop: {
    label: 'CFOP',
    shortLabel: 'CFO/P',
    fullName: 'Cash Flow from Operations per Share',
    tooltip: 'Operating cash flow per share',
    formula: 'operating cash flow / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'cashflow',
    heat: 'column',
  },
  sfcfp: {
    label: 'SFCFP',
    shortLabel: 'SFCF/P',
    fullName: 'Free Cash Flow per Share',
    tooltip: 'Free cash flow per share',
    formula: '(operating cash flow - capex) / shares outstanding',
    source: 'SEC CompanyFacts (derived)',
    group: 'cashflow',
    heat: 'column',
  },
  ncfp: {
    label: 'NCFP',
    shortLabel: 'NCF/P',
    fullName: 'Net Cash Flow per Share',
    tooltip: 'Net cash flow per share',
    group: 'cashflow',
    heat: 'column',
  },
  cashp: {
    label: 'Cash/P',
    shortLabel: 'Cash/P',
    fullName: 'Cash per Share',
    tooltip: 'Cash and equivalents per share',
    group: 'cashflow',
    heat: 'column',
  },
  assetp: {
    label: 'Asset/P',
    shortLabel: 'Asset/P',
    fullName: 'Assets per Share',
    tooltip: 'Total assets per share',
    group: 'cashflow',
    heat: 'column',
  },
  insiderBuy6m: {
    label: 'Insider Buy 6M',
    shortLabel: '6M IB',
    fullName: 'Insider Buying (6 months)',
    tooltip: 'Net insider purchase value, last 6 months',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy3m: {
    label: 'Insider Buy 3M',
    shortLabel: '3M IB',
    fullName: 'Insider Buying (3 months)',
    tooltip: 'Net insider purchase value, last 3 months',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy1m: {
    label: 'Insider Buy 1M',
    shortLabel: '1M IB',
    fullName: 'Insider Buying (1 month)',
    tooltip: 'Net insider purchase value, last 1 month',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4',
    group: 'insider',
    heat: 'insider',
  },
  secLink: { label: 'SEC', shortLabel: 'SEC', group: 'links' },
  wwLink: { label: 'WW', shortLabel: 'WW', group: 'links' },
  saLink: { label: 'SA', shortLabel: 'SA', group: 'links' },
  newsLink: { label: 'News', shortLabel: 'News', group: 'links' },
  chartLink: { label: 'Chart', shortLabel: 'Chart', group: 'links' },
  openInsiderLink: { label: '6M Ins', shortLabel: '6M Ins', group: 'links' },
};
