/** Portfolio grid column metadata (labels, tooltips, formulas, RK groups). */

export const PORTFOLIO_COLUMN_GROUPS = [
  { id: 'quote', label: 'Quote' },
  { id: 'valuation', label: 'Valuation' },
  { id: 'cashflow', label: 'Cash Flow' },
  { id: 'insider', label: 'Insider' },
  { id: 'links', label: 'Links' },
];

export const PORTFOLIO_COLUMN_META = {
  ticker: {
    label: 'Ticker',
    shortLabel: 'Ticker',
    fullName: 'Ticker Symbol',
    tooltip: 'Stock ticker symbol',
    group: 'quote',
    sticky: true,
  },
  price: {
    label: 'Price',
    shortLabel: 'Price',
    fullName: 'Latest Price',
    tooltip: 'Latest closing price (USD)',
    formula: 'Latest close from prices cache',
    source: 'Stooq / yfinance → SQLite prices',
    group: 'quote',
    sticky: true,
  },
  change: {
    label: 'Change',
    shortLabel: 'D% Ch',
    fullName: 'Daily Percent Change',
    tooltip: 'Percent change from previous close',
    formula: '(todayClose - prevClose) / prevClose × 100',
    source: 'SQLite prices (daily change)',
    group: 'quote',
    heat: 'signed',
    heatScale: 5,
  },
  marketCap: {
    label: 'Market Cap',
    shortLabel: 'Mkt Cap',
    fullName: 'Market Capitalization',
    tooltip: 'Market capitalization (USD)',
    formula: 'shares outstanding × latest close',
    source: 'SEC shares + prices',
    group: 'quote',
  },
  sp: {
    label: 'SP',
    shortLabel: 'S/P',
    fullName: 'Sales per Share',
    tooltip: 'Revenue per share',
    formula: 'revenue / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ebitdaEv: {
    label: 'Eb/EV',
    shortLabel: 'Eb/EV',
    fullName: 'EBITDA / Enterprise Value',
    tooltip: 'EBITDA divided by enterprise value',
    formula: 'ebitda / (marketCap + debt - cash)',
    source: 'SEC + prices (derived)',
    group: 'valuation',
    heat: 'column',
  },
  tbp: {
    label: 'TBP',
    shortLabel: 'TB/P',
    fullName: 'Tangible Book per Share',
    tooltip: 'Book value per share (tangible proxy)',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  bp: {
    label: 'BP',
    shortLabel: 'B/P',
    fullName: 'Book Value per Share',
    tooltip: 'Book value per share',
    formula: 'equity / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  ep: {
    label: 'EP',
    shortLabel: 'E/P',
    fullName: 'Earnings per Share',
    tooltip: 'Diluted EPS from latest annual filing',
    formula: 'EPS (diluted)',
    source: 'SEC CompanyFacts',
    group: 'valuation',
    heat: 'column',
  },
  cfop: {
    label: 'CFOP',
    shortLabel: 'CFO/P',
    fullName: 'Cash Flow from Operations per Share',
    tooltip: 'Operating cash flow per share',
    formula: 'operating cash flow / shares outstanding',
    source: 'SEC CompanyFacts',
    group: 'cashflow',
    heat: 'column',
  },
  sfcfp: {
    label: 'SFCFP',
    shortLabel: 'SFCF/P',
    fullName: 'Free Cash Flow per Share',
    tooltip: 'Free cash flow per share',
    formula: '(operating cash flow - capex) / shares outstanding',
    source: 'SEC CompanyFacts (derived)',
    group: 'cashflow',
    heat: 'column',
  },
  insiderBuy6m: {
    label: 'Insider Buy 6M',
    shortLabel: '6M IB',
    fullName: 'Insider Buying (6 months)',
    tooltip: 'Net insider purchase value, last 6 months',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4 / Nasdaq SF2',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy3m: {
    label: 'Insider Buy 3M',
    shortLabel: '3M IB',
    fullName: 'Insider Buying (3 months)',
    tooltip: 'Net insider purchase value, last 3 months',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4 / Nasdaq SF2',
    group: 'insider',
    heat: 'insider',
  },
  insiderBuy1m: {
    label: 'Insider Buy 1M',
    shortLabel: '1M IB',
    fullName: 'Insider Buying (1 month)',
    tooltip: 'Net insider purchase value, last 1 month',
    formula: 'Σ purchases − Σ sales (Form 4, ≥ $10k)',
    source: 'SEC Form 4 / Nasdaq SF2',
    group: 'insider',
    heat: 'insider',
  },
  secLink: { label: 'SEC', shortLabel: 'SEC', group: 'links' },
  wwLink: { label: 'WW', shortLabel: 'WW', group: 'links' },
  saLink: { label: 'SA', shortLabel: 'SA', group: 'links' },
  newsLink: { label: 'News', shortLabel: 'News', group: 'links' },
};
