// Centralized API endpoints — all reads are SQLite-backed after admin bootstrap.
// Data sources: SEC EDGAR (fundamentals, insiders), Stooq/yfinance (prices), RSS (news).
// Routes read SQLite/Stooq/SEC only; bootstrap via Admin when cache is empty.
const API_BASE = '/api';

export const API_ENDPOINTS = {
  SEARCH: `${API_BASE}/search`,
  PREFERENCES: `${API_BASE}/preferences`,
  COMPANY_TAGS: `${API_BASE}/company-tags`,
  SUMMARY: ticker => `${API_BASE}/ticker/${ticker}/summary`,
  NEWS: ticker => `${API_BASE}/ticker/${ticker}/news`,
  NEWS_FEED: `${API_BASE}/news`,
  NEWS_SOURCE_DOMAINS: `${API_BASE}/news/source-domains`,
  NEWS_CLUSTERS: `${API_BASE}/news/clusters`,
  MACRO_SNAPSHOT: `${API_BASE}/macro/snapshot`,
  FINANCIALS: `${API_BASE}/ticker/financials`,
  INTRADAY: ticker => `${API_BASE}/ticker/${ticker}/intraday`,
  TOP_OF_BOOK: `${API_BASE}/tickers/top`,
  DAILY_CHANGE: `${API_BASE}/tickers/daily-change`,
  MARKET_STATS: `${API_BASE}/tickers/market-stats`,
  MOVERS: `${API_BASE}/tickers/movers`,
  INDUSTRIES: `${API_BASE}/companies/industries`,
  INDUSTRY_PEERS: `${API_BASE}/companies/peers`,
  WATCHLISTS: `${API_BASE}/watchlists`,
  WATCHLIST: name => `${API_BASE}/watchlists/${encodeURIComponent(name)}`,
  WATCHLIST_TICKERS: name => `${API_BASE}/watchlists/${encodeURIComponent(name)}/tickers`,
  WATCHLIST_TICKER: (name, ticker) => `${API_BASE}/watchlists/${encodeURIComponent(name)}/tickers/${encodeURIComponent(ticker)}`,
  RESEARCH_SCREENER: `${API_BASE}/research/screener`,
  RESEARCH_NARRATIVE_DIVERGENCE: `${API_BASE}/research/narrative-divergence`,
  RESEARCH_SCREEN: `${API_BASE}/research/screen`,
  SCREENS: `${API_BASE}/screens`,
  SCREEN: id => `${API_BASE}/screens/${encodeURIComponent(id)}`,
  RESEARCH_RANK: `${API_BASE}/research/rank`,
  RESEARCH_RANK_VALIDATION: `${API_BASE}/research/rank/validation`,
  RESEARCH_RANK_HISTORY: ticker => `${API_BASE}/research/rank/history/${encodeURIComponent(ticker)}`,
  RESEARCH_THESIS_HISTORY: ticker => `${API_BASE}/research/rank/thesis-history/${encodeURIComponent(ticker)}`,
  RESEARCH_QUEUE: `${API_BASE}/research/queue`,
  RESEARCH_CATALYSTS: `${API_BASE}/research/catalysts`,
  RESEARCH_QUEUE_DISMISS: ticker => `${API_BASE}/research/queue/${encodeURIComponent(ticker)}/dismiss`,
  RESEARCH_INSIDER_ALERTS: `${API_BASE}/research/insider-alerts`,
  RESEARCH_NARRATIVE_ALERTS: `${API_BASE}/research/narrative-alerts`,
  SIGNALS: `${API_BASE}/signals`,
  SIGNALS_MORNING_BRIEF: `${API_BASE}/signals/morning-brief`,
  SIGNALS_STATE: `${API_BASE}/signals/state`,
  SIGNALS_DISMISS: `${API_BASE}/signals/dismiss`,
  RESEARCH_METRICS_REGISTRY: `${API_BASE}/research/metrics/registry`,
  RESEARCH_SECTOR_STATS: `${API_BASE}/research/metrics/sector-stats`,
  RESEARCH_TICKER: ticker => `${API_BASE}/research/ticker/${encodeURIComponent(ticker)}`,
  RESEARCH_INSIDERS: ticker => `${API_BASE}/research/insiders/${encodeURIComponent(ticker)}`,
  RESEARCH_INSIDER_CLUSTERS: `${API_BASE}/research/insiders/clusters`,
  RESEARCH_NARRATIVE: ticker => `${API_BASE}/research/narrative/${encodeURIComponent(ticker)}`,
  RESEARCH_GATES: ticker => `${API_BASE}/research/gates/${encodeURIComponent(ticker)}`,
  RESEARCH_PILLARS: ticker => `${API_BASE}/research/pillars/${encodeURIComponent(ticker)}`,
  RESEARCH_THESIS: ticker => `${API_BASE}/research/thesis/${encodeURIComponent(ticker)}`,
  RESEARCH_RANK_BASERATE: `${API_BASE}/research/rank/baserate`,
  INSIDER_BUYING_SUMS: `${API_BASE}/insiders/buying-sums`,
  /** SEC Form 4 insider transactions (SQLite; response keeps SF2-compatible datatable shape). */
  INSIDER_TRANSACTIONS: ticker => `${API_BASE}/ticker/${ticker}/sf2`,
  // legacy client alias — same URL as INSIDER_TRANSACTIONS
  // SF2: ticker => `${API_BASE}/ticker/${ticker}/sf2`,
  ADMIN_STATUS: `${API_BASE}/admin/status`,
  ADMIN_CONFIG: `${API_BASE}/admin/config`,
  ADMIN_PIPELINE_STATUS: `${API_BASE}/admin/pipeline-status`,
  ADMIN_UNIVERSES: `${API_BASE}/admin/universes`,
  ADMIN_UNIVERSE: universe => `${API_BASE}/admin/universes/${encodeURIComponent(universe)}`,
  ADMIN_ENQUEUE_UNIVERSE_INSIDERS: `${API_BASE}/admin/enqueue-universe-insiders`,
  ADMIN_JOB_RUNS: `${API_BASE}/admin/job-runs`,
  ADMIN_DEFAULT_FEEDS: `${API_BASE}/admin/default-feeds`,
  ADMIN_FEED_PACKS: `${API_BASE}/admin/feed-packs`,
  ADMIN_SYNC_COMPANIES: `${API_BASE}/admin/sync-companies`,
  ADMIN_REFRESH_FUNDAMENTALS: `${API_BASE}/admin/refresh-fundamentals`,
  ADMIN_INGEST_DEFAULT_FEEDS: `${API_BASE}/admin/ingest-default-feeds`,
  ADMIN_REFRESH_PRICES: `${API_BASE}/admin/refresh-prices`,
  ADMIN_REFRESH_INSIDERS: `${API_BASE}/admin/refresh-insiders`,
  ADMIN_ENQUEUE_JOB: `${API_BASE}/admin/enqueue-job`,
  ADMIN_DEDUP_ARTICLES: `${API_BASE}/admin/dedup-articles`,
  ADMIN_BOOTSTRAP: `${API_BASE}/admin/bootstrap`,
  ADMIN_REFRESH_MACRO: `${API_BASE}/admin/refresh-macro`,
  ADMIN_BACKFILL_MARKET_REACTIONS: `${API_BASE}/admin/backfill-market-reactions`,
  ADMIN_ENRICH_METADATA: `${API_BASE}/admin/enrich-metadata`,
  ADMIN_ENRICH_ARTICLES: `${API_BASE}/admin/enrich-articles`,
  ADMIN_ENRICH_ARTICLES_STATUS: `${API_BASE}/admin/enrich-articles/status`,
};

export default API_ENDPOINTS;
